# Generated by Django 6.0 on 2026-02-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, default='')),
                ('k', models.IntegerField(default=5)),
                ('document_id', models.IntegerField(blank=True, null=True)),
                ('max_distance', models.FloatField(blank=True, null=True)),
                ('best_distance', models.FloatField(blank=True, null=True)),
                ('sources', models.JSONField(default=list)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
            ],
        ),
    ]
