"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
# The same configuration is available to manage.py, WSGI and ASGI.
# Exported environment variables take precedence over the local file.
load_dotenv(BASE_DIR / ".env")


def env_bool(name, default=False):
    value = os.environ.get(name, str(default)).lower()
    if value not in {"true", "false", "1", "0"}:
        raise ImproperlyConfigured(f"{name} must be true, false, 1 or 0.")
    return value in {"true", "1"}


def env_list(name, default=""):
    return [item.strip() for item in os.environ.get(name, default).split(",") if item.strip()]


DEBUG = env_bool("DJANGO_DEBUG")
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "")
if not SECRET_KEY or (not DEBUG and (len(SECRET_KEY) < 50 or len(set(SECRET_KEY)) < 5 or SECRET_KEY.startswith("django-insecure-"))):
    raise ImproperlyConfigured("Set DJANGO_SECRET_KEY to a strong random secret (at least 50 characters in production).")
ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1" if DEBUG else "")
if not DEBUG and (not ALLOWED_HOSTS or "*" in ALLOWED_HOSTS):
    raise ImproperlyConfigured("Set explicit DJANGO_ALLOWED_HOSTS in production.")

CSRF_TRUSTED_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS")
SECURE_SSL_REDIRECT = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_HSTS_SECONDS = 0 if DEBUG else 3600
# Enable only behind a trusted proxy that overwrites X-Forwarded-Proto.
if env_bool("DJANGO_TRUST_PROXY"):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "/api/"
LOGOUT_REDIRECT_URL = "/accounts/login/"
CSRF_FAILURE_VIEW = "api.views.csrf_failure"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "django.contrib.postgres",
    "pgvector.django",
    "rest_framework",
    "api",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'ragdb' if DEBUG else ''),
        'USER': os.environ.get('POSTGRES_USER', 'raguser' if DEBUG else ''),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'ragpass' if DEBUG else ''),
        'HOST': os.environ.get('POSTGRES_HOST', '127.0.0.1' if DEBUG else ''),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}


if not DEBUG:
    for field in ("NAME", "USER", "PASSWORD", "HOST"):
        if not DATABASES["default"][field]:
            raise ImproperlyConfigured(f"Set the PostgreSQL {field.lower()} environment variable in production.")


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Conservative fixed-window portfolio demo budgets (all visitors share the daily cap).
DEMO_DAILY_LIMIT = int(os.environ.get("DEMO_DAILY_LIMIT", "100"))
DEMO_IP_HOURLY_LIMIT = int(os.environ.get("DEMO_IP_HOURLY_LIMIT", "30"))
DEMO_SESSION_HOURLY_LIMIT = int(os.environ.get("DEMO_SESSION_HOURLY_LIMIT", "10"))
if min(DEMO_DAILY_LIMIT, DEMO_IP_HOURLY_LIMIT, DEMO_SESSION_HOURLY_LIMIT) < 1:
    raise ImproperlyConfigured("Demo limits must be positive integers.")

# Visitor uploads are bounded independently of question/search requests.
DEMO_UPLOAD_DAILY_LIMIT = int(os.environ.get("DEMO_UPLOAD_DAILY_LIMIT", "30"))
DEMO_UPLOAD_IP_HOURLY_LIMIT = int(os.environ.get("DEMO_UPLOAD_IP_HOURLY_LIMIT", "10"))
DEMO_UPLOAD_SESSION_HOURLY_LIMIT = int(os.environ.get("DEMO_UPLOAD_SESSION_HOURLY_LIMIT", "5"))
DEMO_MAX_DOCUMENTS = 5
DEMO_MAX_TEXT_CHARS = 20000
DEMO_MAX_PDF_PAGES = 20
if min(DEMO_UPLOAD_DAILY_LIMIT, DEMO_UPLOAD_IP_HOURLY_LIMIT, DEMO_UPLOAD_SESSION_HOURLY_LIMIT) < 1:
    raise ImproperlyConfigured("Visitor upload limits must be positive integers.")
